title: Your awesome title
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # leave this empty if your site is at the root of the domain
url: "https://alexdemichieli.github.io" # the base hostname & protocol for your site
github_username: alexdemichieli
twitter_username: jekyllrb

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
